config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, get_verification, get_recovery_password

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', get_verification, name='confirm'),
    path('recovery_pass/', get_recovery_password, name='recovery_pass'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# from catalog.models import NULLABLE


NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    first_name = models.CharField(max_length=50, verbose_name='имя')
    last_name = models.CharField(max_length=50, verbose_name='фамилия')

    avatar = models.ImageField(verbose_name='аватар', upload_to='users/', **NULLABLE)
    phone = models.CharField(max_length=15, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    token = models.CharField(max_length=50, verbose_name='token', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegistrationForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2', 'avatar', 'phone', 'country']

users/views.py
import secrets

from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegistrationForm
from users.models import User


# Create your views here.
class UserCreateView(CreateView):
    model = User
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email_confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Для завершения регистрации пройдите по ссылке {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def get_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def get_recovery_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        password = secrets.token_hex(8)
        user.set_password(password)
        user.save()
        send_mail(
            subject='Смена пароля',
            message=f'Ваш новый пароль: {password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
    return render(request, 'users/get_recovery_password.html')

users/templates/users/get_recovery_password.html
{% extends 'catalog/base_product.html' %}
{% load tags %}
{% block cam %}
<div class="row text-center">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card mb-6 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Восстановление пароля</h4>
                </div>
                <div class="card-body">
                    <div class="row-3">
                        {% csrf_token %}
                        <input name="email" class="form-control mb-2" placeholder="Email" type="email">
                        <button type="submit" class="btn btn-primary">
                            Получить новый пароль
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base_product.html' %}
{% load tags %}
{% block cam %}
<div class="row text-center">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card mb-6 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Авторизация пользователя</h4>
                </div>
                <div class="card-body">
                    <div class="row-3">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="me-5 btn btn-primary">
                            Войти
                        </button>
                        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:recovery_pass' %}">Забыли пароль?</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base_product.html' %}
{% load tags %}
{% block cam %}
<div class="row text-center">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card mb-6 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Регистрация пользователя</h4>
                </div>
                <div class="card-body">
                    <div class="row-3">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            Зарегистрироваться
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}