catalog/urls.py
from django.urls import path
from catalog.views import (
    ContactsView,
    ProductListView,
    ProductDetailView,
    BlogListView,
    BlogCreateView,
    BlogUpdateView,
    BlogDetailView,
    BlogDeleteView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='update_blog'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='delete_blog'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('products/', ProductListView.as_view(), name='products'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name='create_product'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete_product'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, get_verification, get_recovery_password

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', get_verification, name='confirm'),
    path('recovery_pass/', get_recovery_password, name='recovery_pass'),
]

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Category(models.Model):
    """
    Модель для категории товаров
    """

    name = models.CharField(max_length=50, verbose_name="Категория", help_text="Введите категорию товара")
    description = models.TextField(verbose_name="Описание", help_text="Введите описание категории", **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Product(models.Model):
    """
    Модель для товаров
    """

    name = models.CharField(
        max_length=50,
        verbose_name="Наименование",
        help_text="Введите наименование товара",
    )
    description = models.TextField(verbose_name="Описание", help_text="Введите описание товара", **NULLABLE)
    image = models.ImageField(
        upload_to="catalog/products",
        verbose_name="Изображение товара",
        help_text="Загрузите изображение товара",
        **NULLABLE,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="Категория",
        help_text="Выберите категорию",
        related_name="products",
    )
    price = models.PositiveIntegerField(verbose_name="Цена за покупку", help_text="Введите цену")
    created_at = models.DateField(verbose_name="Дата создания", help_text="Введите дату", auto_now_add=True)
    update_at = models.DateField(verbose_name="Дата изменения", help_text="Введите дату", auto_now=True)

    owner = models.ForeignKey(User, verbose_name="Владелец", on_delete=models.CASCADE, related_name="owner", **NULLABLE)
    publication = models.BooleanField(verbose_name="Опубликовано", default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["category", "price"]
        permissions = [
            ('can_change_publication_product', 'Может отменять публикацию товара'),
            ('can_change_description_product', 'Может менять описание товара'),
            ('can_change_category_product', 'Может менять категорию товара'),
        ]


class Blog(models.Model):
    """
    Модель для блога
    """

    title = models.CharField(max_length=150, verbose_name="Заголовок")
    slug = models.CharField(max_length=150, verbose_name="slug", **NULLABLE)
    content = models.TextField(verbose_name="Содержимое", **NULLABLE)
    preview = models.ImageField(upload_to="blog/", verbose_name="Отправить изображение", **NULLABLE)
    created_at = models.DateField(verbose_name="Дата создания", auto_now_add=True)
    publication = models.BooleanField(verbose_name="Опубликовано", default=True)
    number_of_views = models.PositiveIntegerField(verbose_name="Количество просмотров", default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        ordering = ["created_at"]


class Version(models.Model):
    """
    Модель для версий товаров
    """

    product = models.ForeignKey(Product, on_delete=models.SET_NULL, verbose_name='Товар', **NULLABLE)
    number_version = models.PositiveIntegerField(verbose_name='Номер версии', default=1)
    name_version = models.CharField(max_length=255, verbose_name='Название версии')
    current_version_indicator = models.BooleanField(verbose_name='Признак текущей версии', default=True)

    def __str__(self):
        return self.name_version

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

catalog/forms.py
from django.forms import ModelForm, forms, BooleanField

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at', 'owner')

    def clean_name(self):
        word_danger = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')
        cleaned_data = self.cleaned_data['name']
        if cleaned_data in word_danger:
            raise forms.ValidationError('Название запрещено. Введите другое название!')
        return cleaned_data

    def clean_description(self):
        word_danger = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')
        cleaned_data = self.cleaned_data['description']
        cleaned_data_sort = cleaned_data.lower().replace(',', "").split()
        if list(set(cleaned_data_sort) & set(word_danger)):
            raise forms.ValidationError('Использованы запрещенные слова!')
        return cleaned_data


class ProductModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'publication')


class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm

from catalog.models import Product, Category, Blog, Version


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

    def get_context_data(self, **kwargs):
        if self.request.method == 'POST':
            name = self.request.POST.get('name')
            phone = self.request.POST.get('phone')
            message = self.request.POST.get('message')
            with open('data/contacts.json', 'a', encoding='utf-8') as file:
                json.dump({'name': name, 'phone': phone, 'message': message}, file)
        return super().get_context_data(**kwargs)


class ProductListView(ListView):
    model = Product

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')
    login_url = "/users/login/"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')
    login_url = "/users/login/"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm('catalog.can_change_description_product') and user.has_perm(
                'catalog.can_change_category_product') and user.has_perm('catalog.can_change_publication_product'):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products')
    login_url = "/users/login/"
    redirect_field_name = "redirect_to"


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'slug', 'content', 'preview')
    success_url = reverse_lazy('catalog:home')
    login_url = "/users/login/"
    redirect_field_name = "redirect_to"

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save()
            blog.slug = slugify(blog.title)
            blog.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'slug', 'content', 'preview')
    login_url = "/users/login/"
    redirect_field_name = "redirect_to"

    def get_success_url(self):
        return reverse('catalog:blog_detail', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication=True)
        return queryset


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:home')
    login_url = "/users/login/"
    redirect_field_name = "redirect_to"


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        return self.object

catalog/templates/catalog/blog_confirm_delete.html
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products' %}">Каталог товаров</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">На главную</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-6 box-shadow">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-body">
                        <div class="row-3">
                            {% csrf_token %}
                            <div class="card-text">Хотите удалить статью "{{ object.title }}"?</div>
                            <button type="submit" class="btn btn-danger">
                                Удалить
                            </button>
                            <a class="p-2 btn btn-outline-secondary" href="{% url 'catalog:home' %}">Отмена</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    SkyStore
                    <small class="d-block mb-3 text-muted">&copy; 2023</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Категории</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Рассылки</a></li>
                        <li><a class="text-muted" href="#">Телеграм боты</a></li>
                        <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                        <li><a class="text-muted" href="#">Веб-приложения</a></li>
                        <li><a class="text-muted" href="#">Микросервисы</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Мы пишем</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </footer>

    </div>
</div>
<script src='{% static "js/bootstrap.bundle.min.js" %}'></script>
</body>
</html>

catalog/templates/catalog/blog_detail.html
{% load static %}
{% load tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products' %}">Каталог товаров</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">На главную</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Видеонаблюдение</h1>
    <p class="lead">Статьи</p>
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:create_blog' %}">Написать статью</a>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <img class="mb-2" src="{{ object.preview | media_filter }}" width="240" height="190">
                    <ul class="list-unstyled mt-3 mb-6 text-start m-2">
                        <li>- {{ object.content }}</li>
                        <li>- Дата публикации {{ object.created_at }}</li>
                        <li>- Кол-во просмотров: {{ object.number_of_views }}</li>
                        <li>- {{ object.slug }}</li>
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:update_blog' object.pk %}">Отредактировать
                        статью</a>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src='{% static "js/bootstrap.bundle.min.js" %}'></script>
</body>
</html>

catalog/templates/catalog/blog_form.html
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products' %}">Каталог товаров</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">На главную</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-6">
            <div class="card mb-6 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Статья</h4>
                </div>
                <form method="post" enctype="multipart/form-data">
                    <div class="card-body">
                        <div class="row-3">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    SkyStore
                    <small class="d-block mb-3 text-muted">&copy; 2023</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Категории</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Рассылки</a></li>
                        <li><a class="text-muted" href="#">Телеграм боты</a></li>
                        <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                        <li><a class="text-muted" href="#">Веб-приложения</a></li>
                        <li><a class="text-muted" href="#">Микросервисы</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Мы пишем</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </footer>

    </div>
</div>
    <script src='{% static "js/bootstrap.bundle.min.js" %}'></script>
</body>
</html>

catalog/templates/catalog/blog_list.html
{% load static %}
{% load tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products' %}">Каталог товаров</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Видеонаблюдение</h1>
    <p class="lead">Статьи</p>
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:create_blog' %}">Написать статью</a>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <img class="mb-2" src="{{ object.preview | media_filter }}" width="240" height="190">
                    <ul class="list-unstyled mt-3 mb-6 text-start m-2">
                        <li>- {{ object.content }}</li>
                        <li>- Дата публикации {{ object.created_at }}</li>
                        <li>- Кол-во просмотров: {{ object.number_of_views }}</li>
                        <li>- {{ object.slug }}</li>
                    </ul>
                    <a class="p-2 btn btn-link mb-2" href="{% url 'catalog:blog_detail' object.pk %}">Читать
                        далее</a>
                </div>
                <div class="card-footer">

                    <a class="p-2 btn btn-outline-primary mb-2" href="{% url 'catalog:update_blog' object.pk %}">Отредактировать
                        статью</a>
                    <a class="p-2 btn btn-outline-danger" href="{% url 'catalog:delete_blog' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src='{% static "js/bootstrap.bundle.min.js" %}'></script>
</body>
</html>

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base_product.html' %}
{% load tags %}
{% block cam %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <img src="{{ object.image | media_filter }}">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ object.price }}<small
                        class="text-body-secondary fw-light"> rub</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>{{ object.description }}</li>
                    <li>{{ object.owner }}</li>
                    {% if object.update_at %}
                    <li>{{ object.update_at }}</li>
                    {% else %}
                    <li>{{ object.created_at }}</li>
                    {% endif %}
                </ul>
                {% if user == object.owner or perms.catalog.can_change_description_product and perms.catalog.can_change_category_product and perms.catalog.can_change_publication_product %}
                    <a class="btn btn-outline-secondary mb-3" href="{% url 'catalog:update_product' object.pk %}"
                        role="button">Отредактировать товар</a>
                    {% if user == object.owner %}
                        <a class="btn btn-outline-danger mb-4" href="{% url 'catalog:delete_product' object.pk %}"
                            role="button">Удалить товар</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base_product.html' %}
{% load tags %}
{% block cam %}
<div class="d-flex flex-row-reverse">
    <div class="p-2">
        {% if user.is_authenticated%}
        <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}" role="button">Добавить товар</a>
        {% endif %}
    </div>
</div>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for cam in object_list %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <img src="{{ cam.image | media_filter }}">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ cam.name }}</h4>
                {% for version in cam.version_set.all %}
                    {% if version.current_version_indicator %}
                        <p> Версия: {{ version.name_version }}</p>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ cam.price }}<small
                        class="text-body-secondary fw-light"> rub</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>{{ cam.description }}</li>
                    {% if cam.update_at %}
                    <li>{{ cam.update_at }}</li>
                    {% else %}
                    <li>{{ cam.created_at }}</li>
                    {% endif %}
                </ul>
                <a class="btn btn-primary" href="{% url 'catalog:product_detail' cam.pk %}" role="button">Описание</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}